from github import Github
from github.Repository import Repository
import base64


class GitOpsBridge:
	def __init__(self, token: str, repo_name: str):
		self.gh = Github(token)
		self.repo: Repository = self.gh.get_repo(repo_name)
		self.agent_branch_prefix = "agent/"

	async def create_agent_branch(self, task_id: str, base: str = "main") -> str:
		"""Агент НИКОГДА не пишет в main напрямую"""
		branch_name = f"{self.agent_branch_prefix}{task_id}"
		source = self.repo.get_branch(base)
		self.repo.create_git_ref(
			ref=f"refs/heads/{branch_name}",
			sha=source.commit.sha
		)
		return branch_name

	async def commit_files(
		self,
		branch: str,
		files: dict[str, str],
		commit_message: str,
		task_metadata: dict
	) -> str:
		"""Atomic commit нескольких файлов через Git Trees API"""
		base_commit = self.repo.get_branch(branch).commit

		# Создаём tree с новыми файлами
		tree_elements = []
		for path, content in files.items():
			blob = self.repo.create_git_blob(
				content=content,
				encoding="utf-8"
			)
			tree_elements.append({
				"path": path,
				"mode": "100644",
				"type": "blob",
				"sha": blob.sha
			})

		new_tree = self.repo.create_git_tree(
			tree=tree_elements,
			base_tree=base_commit.commit.tree
		)

		# Commit с метаданными агента в теле
		new_commit = self.repo.create_git_commit(
			message=f"{commit_message}\n\nAgent-Task-ID: {task_metadata['task_id']}\nAgent-Model: {task_metadata['model']}\nTokens-Used: {task_metadata['tokens']}",
			tree=new_tree,
			parents=[base_commit.commit]
		)

		self.repo.get_git_ref(f"heads/{branch}").edit(sha=new_commit.sha)
		return new_commit.sha

	async def create_pr_for_approval(
		self, branch: str, task_summary: str
	) -> str:
		"""PR = точка входа для Human Approval"""
		pr = self.repo.create_pull(
			title=f"[AI Agent] {task_summary[:72]}",
			body=self._generate_pr_body(branch),
			head=branch,
			base="main",
			draft=True  # Draft until conductor approves
		)
		return pr.html_url

	def _generate_pr_body(self, branch: str) -> str:
		return """## AI Agent Pull Request
> ⚠️ This PR was generated by an AI agent. Review required before merge.

### Approval Checklist
- [ ] Architecture decisions reviewed in Approval Gateway
- [ ] Security findings addressed
- [ ] Test coverage ≥ 80%
- [ ] Conductor approved via UI

### Review in Approval Gateway
[Open in Langfuse Dashboard](http://localhost:3000)
"""
